language: python

sudo: required
services:
  - docker
before_install:
  - gem install package_cloud
  - pip3 install jinja2
before_script:
  - sudo chown root:root */*
script:
  - make all
  - if [[ "$RPM_GPG_KEY_SECRET" != "" ]]; then openssl aes-256-cbc -k "$RPM_GPG_KEY_SECRET" -in secret.asc.enc -out secret.asc -d; fi
  - if [[ "$RPM_GPG_KEY_PASSPHRASE" != "" ]]; then echo "$RPM_GPG_KEY_PASSPHRASE" > .passphrase; fi
  - if [[ "$TRAVIS_REPO_SLUG" == "lest/prometheus-rpm" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then make publish; fi
